// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apwaeetfagjhoxxqlbjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwd2FlZXRmYWdqaG94eHFsYmpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NTY1MzEsImV4cCI6MjA1NzAzMjUzMX0.2dQCw2CkSRUBKuD5seNZ8nexqr7n1YB6NqUWELVeKLE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);